"""
Cartographer -- map coverage / vanquish bot widget.

Status: UI + persistent stores (task 3 of the build plan). Pathing, combat
and the actual run modes land in later tasks; the Start button is a stub.

Layout:
  lib/map_names.py    -- map id <-> name lookups (offline-safe)
  lib/portal_graph.py -- the generated portal graph ("csv of truth")
  lib/stores.py       -- JSON persistence under Widgets/Config/Cartographer/
  data/portal_graph_v2.csv -- generated by the old repo's gwdat_tools
                              pipeline; never hand-edit, regenerate + copy.
"""
import importlib.util
import math
import os
import traceback

import PyImGui
from Py4GWCoreLib import Map
from Py4GWCoreLib.Agent import Agent
from Py4GWCoreLib.Item import Item
from Py4GWCoreLib.Player import Player
from Py4GWCoreLib.Overlay import Overlay
from Py4GWCoreLib import Color
from Py4GWCoreLib.GlobalCache import GLOBAL_CACHE
from Py4GWCoreLib.Pathing import AutoPathing, AStar

MODULE_NAME = "Cartographer"

_DIR = os.path.dirname(os.path.abspath(__file__))


def _load_lib(name: str):
    spec = importlib.util.spec_from_file_location(
        f"cartographer_lib_{name}", os.path.join(_DIR, "lib", f"{name}.py")
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_load_error: str | None = None
try:
    map_names = _load_lib("map_names")
    portal_graph = _load_lib("portal_graph")
    gwtoolbox_portal_graph = _load_lib("gwtoolbox_portal_graph")
    stores = _load_lib("stores")
    routing = _load_lib("routing")
    pathing_ext = _load_lib("pathing_ext")
    coverage = _load_lib("coverage")
    combat = _load_lib("combat")
    party_lib = _load_lib("party")
    titles = _load_lib("titles")
    runner = _load_lib("runner")

    portal_graph.load()
    gwtoolbox_portal_graph.load()
    settings = stores.Settings()
    healer_ids = stores.IdListStore("healer_model_ids.json")
    maps_vanquished = stores.IdListStore("maps_vanquished.json")
    maps_cartographed = stores.IdListStore("maps_cartographed.json")
    combat_ctl = combat.CombatController(settings, healer_ids)
except Exception:
    _load_error = traceback.format_exc()


MODES = ["single", "route", "list"]
MODE_LABELS = ["Single map", "Route", "List"]

# transient UI state (not persisted)
_ui_healer_id_input = 0
_ui_loot_model_id_input = 0
_run_ctx = None  # runner.RunContext of the current/last bot run
_route_cache: dict = {"key": None, "route": None}
_target_track = {"id": 0, "model_id": 0}
_wp_draw = {"show": False, "count": 100}  # "Draw next N waypoints" toggle
_portal_overlay = {"show": False}  # "Draw all portals + no-go zones" toggle


def _active_portal_graph():
    """Which portal-graph module to use for routing/pathing this frame:
    our own discovery pipeline, or GWToolboxpp's static hand-curated list
    (Settings.use_gwtoolbox_routing). Both expose the identical API
    (load/adjacency/neighbors/portal_position/portal_markers/known_map_ids)
    so every caller can just swap the module reference."""
    return gwtoolbox_portal_graph if settings.use_gwtoolbox_routing else portal_graph


def _current_target_model_id() -> int:
    """Model id of the current target: item model for a dropped item,
    agent model for anything living. 0 if no/unknown target."""
    try:
        tid = Player.GetTargetID()
        if tid <= 0:
            return 0
        item_agent = Agent.GetItemAgentByID(tid)
        if item_agent is not None and item_agent.item_id:
            return int(Item.GetModelID(item_agent.item_id) or 0)
        return int(Agent.GetModelID(tid) or 0)
    except Exception:
        return 0


def _track_target_model_id():
    """Keep the healer/loot model_id input fields following the current
    target (updated on target change, so the fields stay hand-editable)."""
    global _ui_healer_id_input, _ui_loot_model_id_input
    try:
        tid = Player.GetTargetID()
    except Exception:
        tid = 0
    if tid == _target_track["id"]:
        return
    _target_track["id"] = tid
    mid = _current_target_model_id()
    _target_track["model_id"] = mid
    if mid > 0:
        _ui_healer_id_input = mid
        _ui_loot_model_id_input = mid


def _resolve(name: str) -> int | None:
    return map_names.resolve_map_id_by_name(
        name, prefer_ids=_active_portal_graph().known_map_ids()
    )


def _route_preview(start_name: str, target_name: str, prevent_outposts: bool):
    """Cached BFS route preview for the Main tab (recomputes on input change)."""
    start, target = _resolve(start_name), _resolve(target_name)
    if start is None or target is None:
        return None
    key = (start, target, prevent_outposts, settings.use_gwtoolbox_routing)
    if _route_cache["key"] != key:
        _route_cache["key"] = key
        _route_cache["route"] = routing.shortest_route(
            _active_portal_graph(), map_names, start, target, prevent_outposts
        )
    return _route_cache["route"]


def _checkbox(label: str, key: str):
    """Draw a checkbox bound to a settings attribute; mark dirty on change."""
    old = getattr(settings, key)
    new = PyImGui.checkbox(label, old)
    if new != old:
        setattr(settings, key, new)
        settings.mark_dirty()


def _text_input(label: str, key: str, buf: int = 128):
    old = getattr(settings, key)
    new = PyImGui.input_text(label, old, buf)
    if new != old:
        setattr(settings, key, new)
        settings.mark_dirty()


def _map_name_feedback(name: str):
    """Show how a typed map name resolves (green id or red unknown)."""
    if not name.strip():
        return
    mid = map_names.resolve_map_id_by_name(name, prefer_ids=_active_portal_graph().known_map_ids())
    if mid is None:
        PyImGui.text_colored("  -> unknown map name", (1.0, 0.35, 0.35, 1.0))
    else:
        kind = "outpost" if map_names.is_outpost(mid) else "explorable"
        in_graph = mid in _active_portal_graph().adjacency()
        note = "" if in_graph else ", NOT in portal graph"
        PyImGui.text_colored(
            f"  -> {map_names.MAP_ID_TO_NAME[mid]} ({mid}, {kind}{note})",
            (0.5, 1.0, 0.5, 1.0) if in_graph else (1.0, 0.8, 0.3, 1.0),
        )


_team_prep = {"running": False, "message": ""}


def _team_prep_coro():
    msgs = []

    def log(m):
        msgs.append(str(m))

    try:
        ok = yield from party_lib.prepare_team_coro(log=log)
        _team_prep["message"] = msgs[-1] if msgs else str(ok)
    except Exception:
        _team_prep["message"] = "prepare team crashed: " + traceback.format_exc()
    finally:
        _team_prep["running"] = False


def _draw_main_tab():
    global _run_ctx
    PyImGui.text("Toggles")
    _checkbox("Hardmode", "hardmode")
    _checkbox("Vanquish", "vanquish")
    _checkbox("Cartographer", "cartographer")
    _checkbox("Skip already vanquished maps", "skip_vanquished")
    _checkbox("Use GWToolbox routing (static 341-map list, not our own discovery graph)",
              "use_gwtoolbox_routing")
    PyImGui.separator()

    mode_index = MODES.index(settings.mode) if settings.mode in MODES else 0
    new_index = PyImGui.combo("Mode", mode_index, MODE_LABELS)
    if new_index != mode_index:
        settings.mode = MODES[new_index]
        settings.mark_dirty()
    PyImGui.separator()

    if settings.mode == "route":
        _text_input("Start map", "route_start_map")
        _map_name_feedback(settings.route_start_map)
        _text_input("Target map", "route_target_map")
        _map_name_feedback(settings.route_target_map)
        _checkbox("Prevent outposts", "route_prevent_outposts")
        _checkbox("Skip start map completion", "route_skip_start_map")
        route = _route_preview(
            settings.route_start_map,
            settings.route_target_map,
            settings.route_prevent_outposts,
        )
        if settings.route_start_map.strip() and settings.route_target_map.strip():
            PyImGui.separator()
            if route is None and _resolve(settings.route_start_map) is not None \
                    and _resolve(settings.route_target_map) is not None:
                PyImGui.text_colored(
                    "No route found under these constraints.", (1.0, 0.35, 0.35, 1.0)
                )
            elif route is not None:
                PyImGui.text(f"Route ({len(route) - 1} portal crossings):")
                for mid in route:
                    PyImGui.bullet_text(
                        f"{map_names.MAP_ID_TO_NAME.get(mid, '?')} ({mid})"
                    )
    elif settings.mode == "list":
        PyImGui.text("Maps (one per line):")
        new_text = PyImGui.input_text_multiline(
            "##list_maps", settings.list_maps_text, (350, 120), 0
        )
        if new_text != settings.list_maps_text:
            settings.list_maps_text = new_text
            settings.mark_dirty()
        unresolved = []
        resolved = []
        for line in settings.list_maps_text.splitlines():
            if not line.strip():
                continue
            mid = map_names.resolve_map_id_by_name(
                line, prefer_ids=_active_portal_graph().known_map_ids()
            )
            (resolved if mid is not None else unresolved).append(line.strip())
        PyImGui.text(f"{len(resolved)} maps resolved")
        if unresolved:
            PyImGui.text_colored(
                "Unknown: " + ", ".join(unresolved), (1.0, 0.35, 0.35, 1.0)
            )
        _checkbox("Prevent outposts", "list_prevent_outposts")
        _checkbox("Maximize group size", "list_maximize_group_size")
    else:
        PyImGui.text("Runs coverage/vanquish on the current map.")

    PyImGui.separator()
    if PyImGui.button("Prepare team (kick all, add heroes, verify builds)") \
            and not _team_prep["running"]:
        _team_prep.update(running=True, message="")
        GLOBAL_CACHE.Coroutines.append(_team_prep_coro())
    if _team_prep["running"]:
        PyImGui.text("Preparing team...")
    elif _team_prep["message"]:
        PyImGui.text(_team_prep["message"])

    PyImGui.separator()
    if _run_ctx is None or not _run_ctx.running:
        if PyImGui.button("Start"):
            _run_ctx = runner.RunContext(
                settings=settings,
                combat_ctl=combat_ctl,
                portal_graph=_active_portal_graph(),
                map_names=map_names,
                routing=routing,
                pathing_ext=pathing_ext,
                coverage=coverage,
                party_lib=party_lib,
                titles=titles,
                maps_vanquished=maps_vanquished,
                maps_cartographed=maps_cartographed,
                config_dir=stores.CONFIG_DIR,
            )
            GLOBAL_CACHE.Coroutines.append(runner.run_coro(_run_ctx))
    else:
        if _run_ctx.paused:
            PyImGui.text_colored(f"Paused: {_run_ctx.status}",
                                 (1.0, 0.8, 0.3, 1.0))
        else:
            PyImGui.text_colored(f"Running: {_run_ctx.status}",
                                 (0.5, 1.0, 0.5, 1.0))
        if PyImGui.button("Stop"):
            _run_ctx.stop_requested = True
            _run_ctx.status = "stopping..."
        PyImGui.same_line(0, 10)
        if PyImGui.button("Resume" if _run_ctx.paused else "Pause"):
            _run_ctx.paused = not _run_ctx.paused
        PyImGui.same_line(0, 10)
        if PyImGui.button("Skip map"):
            _run_ctx.skip_map_requested = True
    if _run_ctx is not None:
        if not _run_ctx.running and _run_ctx.status:
            PyImGui.text(_run_ctx.status)
        _wp_draw["show"] = PyImGui.checkbox(
            f"Draw next {_wp_draw['count']} waypoints (where the bot wants to go)",
            _wp_draw["show"])
        if _run_ctx.log_lines:
            PyImGui.separator()
            PyImGui.text("Run log:")
            for line in _run_ctx.log_lines:
                PyImGui.text(line)


def _draw_loot_tab():
    global _ui_loot_model_id_input
    _track_target_model_id()
    PyImGui.text("Pick up by rarity/type:")
    for rarity in stores.LOOT_RARITIES:
        old = settings.loot_rarities.get(rarity, False)
        new = PyImGui.checkbox(rarity, old)
        if new != old:
            settings.loot_rarities[rarity] = new
            settings.mark_dirty()
    _checkbox("Lockpicks", "loot_lockpicks")
    PyImGui.separator()

    PyImGui.text("Always pick up these model_ids:")
    if _target_track["model_id"] > 0:
        PyImGui.text(f"(current target: model_id {_target_track['model_id']})")
    _ui_loot_model_id_input = PyImGui.input_int("##loot_model_id", _ui_loot_model_id_input)
    PyImGui.same_line(0, 5)
    if PyImGui.button("Add##loot") and _ui_loot_model_id_input > 0:
        if _ui_loot_model_id_input not in settings.loot_model_ids:
            settings.loot_model_ids.append(_ui_loot_model_id_input)
            settings.mark_dirty()
    for mid in list(settings.loot_model_ids):
        PyImGui.bullet_text(str(mid))
        PyImGui.same_line(0, 10)
        if PyImGui.button(f"Remove##loot_{mid}"):
            settings.loot_model_ids.remove(mid)
            settings.mark_dirty()


def _draw_stores_tab():
    global _ui_healer_id_input
    _track_target_model_id()
    PyImGui.text("Healer model_ids (targets prioritized in combat;")
    PyImGui.text("auto-learned when a target casts monk skills):")
    if _target_track["model_id"] > 0:
        PyImGui.text(f"(current target: model_id {_target_track['model_id']})")
    _ui_healer_id_input = PyImGui.input_int("##healer_id", _ui_healer_id_input)
    PyImGui.same_line(0, 5)
    if PyImGui.button("Add##healer") and _ui_healer_id_input > 0:
        healer_ids.add(_ui_healer_id_input)
    for mid in list(healer_ids.ids):
        PyImGui.bullet_text(str(mid))
        PyImGui.same_line(0, 10)
        if PyImGui.button(f"Remove##healer_{mid}"):
            healer_ids.remove(mid)
    PyImGui.separator()

    for label, store in (
        ("Vanquished", maps_vanquished),
        ("Cartographed", maps_cartographed),
    ):
        PyImGui.text(f"{label} maps: {len(store.ids)}")
        for mid in list(store.ids):
            name = map_names.MAP_ID_TO_NAME.get(mid, "?")
            PyImGui.bullet_text(f"{name} ({mid})")
            PyImGui.same_line(0, 10)
            if PyImGui.button(f"Remove##{label}_{mid}"):
                store.remove(mid)
        PyImGui.separator()


# live path-planning test (Data tab): plan player -> a chosen known exit,
# with 800u no-go zones on every OTHER portal, and optionally draw it.
_path_test = {"running": False, "result": None, "error": None, "draw": False}


def _path_test_coro(target_exit):
    try:
        map_id = Map.GetMapID()
        ap = AutoPathing()
        yield from ap.load_pathing_maps()
        navmesh = ap.get_navmesh()
        if navmesh is None:
            _path_test["error"] = "navmesh not available"
            return
        player_id = Player.GetAgentID()
        px, py, _pz = Agent.GetXYZ(player_id)
        zones = pathing_ext.zones_for_map(
            _active_portal_graph(), map_id, map_completed=True,
            target_neighbor=target_exit.neighbor_id,
        )
        yield
        path = pathing_ext.plan_path_avoiding(
            navmesh, AStar, (px, py),
            (target_exit.portal_x, target_exit.portal_y), zones,
        )
        if path is None:
            _path_test["error"] = "no route found (zones too tight?)"
        else:
            _path_test["result"] = {
                "target": f"{target_exit.neighbor_name} ({target_exit.neighbor_id})",
                "waypoints": path,
                "length": pathing_ext.path_length(path),
                "zones": zones.circles,
                "target_portal": (target_exit.portal_x, target_exit.portal_y),
            }
    except Exception:
        _path_test["error"] = traceback.format_exc()
    finally:
        _path_test["running"] = False


def _draw_polyline_3d(overlay, points, color, thickness=3.0):
    for (x1, y1), (x2, y2) in zip(points, points[1:]):
        if not GLOBAL_CACHE.Camera.IsPointInFOV(x1, y1) \
                or not GLOBAL_CACHE.Camera.IsPointInFOV(x2, y2):
            continue
        z1 = overlay.FindZ(x1, y1)
        z2 = overlay.FindZ(x2, y2)
        overlay.DrawLine3D(x1, y1, z1, x2, y2, z2, color, thickness)


def _draw_zones_3d(overlay, circles):
    for cx, cy, r in circles:
        if not GLOBAL_CACHE.Camera.IsPointInFOV(cx, cy):
            continue
        z = overlay.FindZ(cx, cy)
        overlay.DrawPoly3D(cx, cy, z, r,
                           Color(255, 60, 60, 200).to_color(), 48, 4.0, False)


def _draw_portal_arrow_3d(overlay, x, y, color, label=None,
                          shaft_height=300.0, head_size=90.0):
    """A location marker at (x, y): a vertical pole plus 4 lines
    converging from a ring at the pole's top down to the ground point,
    forming a downward-pointing "funnel" silhouette. No true portal-facing
    direction is available from the graph data (only a position), so this
    marks WHERE a portal is rather than which way it opens -- a ring of
    converging lines reads as an arrow from any horizontal camera angle,
    unlike a single flat triangle which can go edge-on and vanish."""
    if not GLOBAL_CACHE.Camera.IsPointInFOV(x, y):
        return
    z = overlay.FindZ(x, y)
    top = z + shaft_height
    ring_z = top - head_size
    overlay.DrawLine3D(x, y, top, x, y, ring_z, color, 3.0)
    for ang in (0.0, math.pi / 2, math.pi, 3 * math.pi / 2):
        ox = x + head_size * 0.5 * math.cos(ang)
        oy = y + head_size * 0.5 * math.sin(ang)
        overlay.DrawLine3D(ox, oy, ring_z, x, y, z, color, 3.0)
    if label:
        overlay.DrawText3D(x, y, top, label, color, True, True, 1.0)


def _draw_all_portals_overlay():
    """Diagnostic (user request): every portal on the CURRENT map -- both
    known graph edges (arrow + destination label) and offline/live
    portal-marker props with an unresolved destination (zone only, no
    label -- we don't know where they lead) -- plus the exact no-go zone
    circles zones_for_map() would compute for coverage/vanquish (radius
    PORTAL_ZONE_RADIUS, map_completed=False so every portal is included,
    same as what a coverage walk actually treats as blocked). Recomputed
    fresh every frame off the live current map, not tied to a test button."""
    if not _portal_overlay["show"]:
        return
    try:
        map_id = Map.GetMapID()
    except Exception:
        return
    graph = _active_portal_graph()
    edges = graph.adjacency().get(map_id, [])
    zones = pathing_ext.zones_for_map(graph, map_id, map_completed=False)
    overlay = Overlay()
    overlay.BeginDraw()
    try:
        _draw_zones_3d(overlay, zones.circles)
        arrow_color = Color(0, 220, 255, 255).to_color()
        for e in edges:
            _draw_portal_arrow_3d(overlay, e.portal_x, e.portal_y,
                                  arrow_color, label=e.neighbor_name)
        marker_color = Color(255, 220, 0, 255).to_color()
        known_pos = {(round(e.portal_x), round(e.portal_y)) for e in edges}
        for mx, my in graph.portal_markers(map_id):
            if (round(mx), round(my)) in known_pos:
                continue  # already drawn (with a label) as a known edge
            _draw_portal_arrow_3d(overlay, mx, my, marker_color)
    finally:
        overlay.EndDraw()


def _draw_run_waypoints_overlay():
    """Diagnostic: draw the upcoming coverage waypoints of the ACTUAL run
    (RunContext.current_waypoints/current_waypoint_index, updated live by
    runner.run_single_map) -- separate from the manual "Plan path"/"Plan
    coverage walk" test buttons, this shows what the running bot is
    walking right now, so a stuck/confused run can be diagnosed visually."""
    if not _wp_draw["show"] or _run_ctx is None:
        return
    wps = _run_ctx.current_waypoints
    if not wps:
        return
    idx = _run_ctx.current_waypoint_index
    upcoming = wps[idx:idx + _wp_draw["count"]]
    if len(upcoming) < 2:
        return
    overlay = Overlay()
    overlay.BeginDraw()
    try:
        _draw_polyline_3d(overlay, upcoming, Color(255, 165, 0, 255).to_color(), 3.0)
    finally:
        overlay.EndDraw()


def _draw_path_test_overlay():
    result = _path_test["result"]
    if not result or not _path_test["draw"]:
        return
    overlay = Overlay()
    overlay.BeginDraw()
    try:
        _draw_polyline_3d(overlay, result["waypoints"],
                          Color(0, 255, 0, 255).to_color())
        # exclusion zones in red; the exempted target portal as a green ring
        _draw_zones_3d(overlay, result["zones"])
        tx, ty = result["target_portal"]
        if GLOBAL_CACHE.Camera.IsPointInFOV(tx, ty):
            z = overlay.FindZ(tx, ty)
            overlay.DrawPoly3D(tx, ty, z, pathing_ext.PORTAL_ZONE_RADIUS,
                               Color(60, 255, 60, 200).to_color(), 48, 4.0, False)
    finally:
        overlay.EndDraw()


# live combat-scan readout (Data tab): throttled CombatController.scan()
_combat_scan = {"show": False, "last": 0.0, "state": None}


def _draw_combat_scan():
    import time as _time
    _combat_scan["show"] = PyImGui.checkbox("Show live combat scan",
                                            _combat_scan["show"])
    if not _combat_scan["show"]:
        return
    now = _time.monotonic()
    if now - _combat_scan["last"] >= 0.5:
        _combat_scan["last"] = now
        _combat_scan["state"] = combat_ctl.scan()
    st = _combat_scan["state"]
    if st is None:
        return
    smoothed = combat_ctl.smoothed_in_combat(st)
    PyImGui.text(f"in_combat: {smoothed} (raw scan: {st.in_combat}) | "
                 f"nearest: {st.nearest_id} @ "
                 f"{st.nearest_d if st.nearest_id > 0 else 0:.0f}u")
    PyImGui.text(f"known healer: {st.healer_id} | cluster: {st.cluster_id}")
    PyImGui.text(f"dead party members: {combat_ctl.has_dead_party_members()} | "
                 f"party can res: {combat_ctl.party_can_res()}")
    PyImGui.text(f"true wipe (no living res-carrier): {combat_ctl.is_wiped()}")
    PyImGui.text(f"whitelisted loot in range (opportunistic "
                 f"{combat.OPPORTUNISTIC_LOOT_RADIUS:.0f}u): "
                 f"{len(combat_ctl.nearby_loot(radius=combat.OPPORTUNISTIC_LOOT_RADIUS))}")


# live Cartographer/Vanquisher title progress (Data tab): throttled
# Player.GetTitle reads, plus the run's own delta and history-file log
_titles_view = {"last": 0.0, "snap": None, "history_count": 0}


def _draw_titles_progress():
    import time as _time
    now = _time.monotonic()
    if now - _titles_view["last"] >= 1.0:
        _titles_view["last"] = now
        try:
            _titles_view["snap"] = titles.snapshot()
        except Exception:
            _titles_view["snap"] = None
        _titles_view["history_count"] = len(titles.load_history(stores.CONFIG_DIR))
    snap = _titles_view["snap"]
    if snap is None:
        return
    PyImGui.text("Title progress (live):")
    for line in titles.format_snapshot(snap):
        PyImGui.bullet_text(line)
    if _run_ctx is not None and _run_ctx.titles_start is not None:
        deltas = titles.format_deltas(_run_ctx.titles_start, snap)
        if deltas:
            PyImGui.text("Gained this run:")
            for line in deltas:
                PyImGui.bullet_text(line)
    if _titles_view["history_count"]:
        PyImGui.text(f"History: {_titles_view['history_count']} completed-map "
                     f"row(s) logged to title_history.csv")


# live coverage-walk test (Data tab): generate the full-map coverage
# waypoint order with ALL portals zoned (map_completed=False) and draw it.
_coverage_test = {"running": False, "result": None, "error": None, "draw": False}


def _coverage_test_coro():
    try:
        map_id = Map.GetMapID()
        ap = AutoPathing()
        yield from ap.load_pathing_maps()
        navmesh = ap.get_navmesh()
        if navmesh is None:
            _coverage_test["error"] = "navmesh not available"
            return
        player_id = Player.GetAgentID()
        px, py, _pz = Agent.GetXYZ(player_id)
        zones = pathing_ext.zones_for_map(_active_portal_graph(), map_id,
                                          map_completed=False)
        try:
            live_portals = Map.Pathing.GetTravelPortals() or []
        except Exception:
            live_portals = []
        if live_portals:
            zones.circles.extend(
                (p.x, p.y, pathing_ext.PORTAL_ZONE_RADIUS) for p in live_portals)
        yield
        wps = coverage.generate_coverage_waypoints(navmesh, zones, (px, py))
        if not wps:
            _coverage_test["error"] = "no coverage waypoints generated"
        else:
            _coverage_test["result"] = {
                "waypoints": wps,
                "length": pathing_ext.path_length(wps),
                "zones": zones.circles,
            }
    except Exception:
        _coverage_test["error"] = traceback.format_exc()
    finally:
        _coverage_test["running"] = False


def _draw_coverage_test_overlay():
    result = _coverage_test["result"]
    if not result or not _coverage_test["draw"]:
        return
    overlay = Overlay()
    overlay.BeginDraw()
    try:
        _draw_polyline_3d(overlay, result["waypoints"],
                          Color(80, 160, 255, 255).to_color(), 2.0)
        _draw_zones_3d(overlay, result["zones"])
    finally:
        overlay.EndDraw()


def _draw_data_tab():
    pg = _active_portal_graph()
    edges = pg.load()
    PyImGui.text(f"Portal graph: {len(edges)} directed edges, "
                 f"{len(pg.known_map_ids())} maps"
                 + (" (GWToolbox)" if settings.use_gwtoolbox_routing else ""))
    PyImGui.text(f"Map names: {len(map_names.OUTPOSTS)} outposts, "
                 f"{len(map_names.EXPLORABLES)} explorables")
    PyImGui.text(f"Config dir: {stores.CONFIG_DIR}")
    PyImGui.separator()

    map_id = Map.GetMapID()
    name = map_names.MAP_ID_TO_NAME.get(map_id, "?")
    PyImGui.text(f"Current map: {name} ({map_id})")
    try:
        px, py = Player.GetXY()
        PyImGui.text_colored(f"Player position: ({px:.0f}, {py:.0f})",
                             (0.5, 1.0, 0.5, 1.0))
    except Exception:
        pass
    _portal_overlay["show"] = PyImGui.checkbox(
        "Draw all portals (arrows) + no-go zones on current map",
        _portal_overlay["show"])
    neigh = pg.adjacency().get(map_id, [])
    if neigh:
        PyImGui.text("Known exits:")
        for e in neigh:
            PyImGui.bullet_text(
                f"{e.neighbor_name} ({e.neighbor_id}) at "
                f"({e.portal_x:.0f}, {e.portal_y:.0f}) "
                f"[{e.method}, conf {e.confidence:.2f}]"
            )
            PyImGui.same_line(0, 10)
            if PyImGui.button(f"Plan path##pt_{e.neighbor_id}") \
                    and not _path_test["running"]:
                _path_test.update(running=True, result=None, error=None)
                GLOBAL_CACHE.Coroutines.append(_path_test_coro(e))
    else:
        PyImGui.text("No known exits for this map in the graph.")

    PyImGui.separator()
    _draw_combat_scan()

    PyImGui.separator()
    _draw_titles_progress()

    PyImGui.separator()
    if PyImGui.button("Plan coverage walk (current map)") \
            and not _coverage_test["running"]:
        _coverage_test.update(running=True, result=None, error=None)
        GLOBAL_CACHE.Coroutines.append(_coverage_test_coro())
    if _coverage_test["running"]:
        PyImGui.text("Generating coverage waypoints...")
    elif _coverage_test["error"]:
        PyImGui.text_colored(f"Coverage failed: {_coverage_test['error']}",
                             (1.0, 0.35, 0.35, 1.0))
    elif _coverage_test["result"]:
        r = _coverage_test["result"]
        PyImGui.text(f"Coverage: {len(r['waypoints'])} waypoints, "
                     f"{r['length']:.0f} units walk, "
                     f"{len(r['zones'])} portal zones (all blocked)")
        _coverage_test["draw"] = PyImGui.checkbox(
            "Draw coverage walk in 3D world", _coverage_test["draw"])

    PyImGui.separator()
    if _path_test["running"]:
        PyImGui.text("Planning path...")
    elif _path_test["error"]:
        PyImGui.text_colored(f"Path test failed: {_path_test['error']}",
                             (1.0, 0.35, 0.35, 1.0))
    elif _path_test["result"]:
        r = _path_test["result"]
        PyImGui.text(f"Path to {r['target']}: {len(r['waypoints'])} waypoints, "
                     f"{r['length']:.0f} units, avoiding {len(r['zones'])} portal zones")
        _path_test["draw"] = PyImGui.checkbox("Draw path in 3D world",
                                              _path_test["draw"])


def main():
    # Every begin_tab_item()/begin_tab_bar() below is matched via
    # try/finally, and the whole draw is wrapped in try/except, so a bug
    # in any tab's draw function can never skip our own end_tab_item()/
    # end_tab_bar()/end() calls -- an unbalanced Begin/End or
    # PushStyle/PopStyle here doesn't just break our own window, it
    # corrupts ImGui's stack for whatever the harness draws next this
    # frame (seen previously as "Missing End()"/"Missing PopStyleColor()"
    # errors on unrelated windows like the LaunchBar and Debug console).
    if PyImGui.begin(MODULE_NAME):
        try:
            if _load_error is not None:
                PyImGui.text_colored("Data load FAILED:", (1.0, 0.3, 0.3, 1.0))
                PyImGui.text(_load_error)
            else:
                if PyImGui.begin_tab_bar("##CartographerTabs"):
                    try:
                        if PyImGui.begin_tab_item("Main"):
                            try:
                                _draw_main_tab()
                            finally:
                                PyImGui.end_tab_item()
                        if PyImGui.begin_tab_item("Loot"):
                            try:
                                _draw_loot_tab()
                            finally:
                                PyImGui.end_tab_item()
                        if PyImGui.begin_tab_item("Stores"):
                            try:
                                _draw_stores_tab()
                            finally:
                                PyImGui.end_tab_item()
                        if PyImGui.begin_tab_item("Data"):
                            try:
                                _draw_data_tab()
                            finally:
                                PyImGui.end_tab_item()
                    finally:
                        PyImGui.end_tab_bar()
                settings.tick()
        except Exception:
            PyImGui.text_colored("Cartographer draw error (see log):",
                                 (1.0, 0.3, 0.3, 1.0))
            PyImGui.text(traceback.format_exc().splitlines()[-1])
    PyImGui.end()
    if _load_error is None:
        try:
            _draw_path_test_overlay()
            _draw_coverage_test_overlay()
            _draw_run_waypoints_overlay()
            _draw_all_portals_overlay()
        except Exception:
            pass


if __name__ == "__main__":
    main()
